[tool.poetry]
name = "fexservice"
version = "0.1.0"
description = ""
authors = ["Paulo Macedo <macedopham@gmail.com>"]

[tool.poetry.scripts]
fexservice = "fexservice.cli:cli"

[tool.poetry.dependencies]
python = "^3.8"
dynaconf = "^2.2.3"
pygithub = "^1.47"
sqlalchemy = "^1.3.15"
dataset = "^1.3.0"
typer = {version = "^0.1.0", extras = ["all"]}
psycopg2-binary = "^2.8.4"
loguru = "^0.4.1"
schedule = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
ipython = "^7.13.0"
ipdb = "^0.13.2"
isort = "^4.3.21"
black = "^19.10b0"
pylint = "^2.4.4"
mypy = "^0.770.0"
sqlalchemy-stubs = "^0.3"
towncrier = "^19.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
